### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by haideralimughal** [HUANGLIZI/LViT#17]
Hello, and thank you so much for your fantastic work. I have a question about the test_model.py file. Regardless of whether I pasted the entire path to my c directory with the dataset name, I always get this issue when I try to run this program. I am unable to fix the problem, though. Please provide me with some advice, and I appreciate it in advance. I may be experiencing problems with my packages, or possibly the issue is actually with the path directory. 

C:\Users\lenovo\anaconda3\envs\trans\python.exe C:\Users\lenovo\PycharmProjects\Lvt\test_model.py 
Traceback (most recent call last):
  File "C:\Users\lenovo\PycharmProjects\Lvt\test_model.py", line 78, in <module>
    checkpoint = torch.load(model_path, map_location='cuda')
  File "C:\Users\lenovo\anaconda3\envs\trans\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\lenovo\anaconda3\envs\trans\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\lenovo\anaconda3\envs\trans\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/lenovo/PycharmProjects/Lvt/MoNuSeg/LViT/test_session_05.24_16h30/models/best_model-LViT.pth.tar'

**Comment by HUANGLIZI** [comment]
The dir is an example dir for pretrained model to test its performance. And you should replace the dir to the dir of your own pretrained model. If you have any else question, you can drop me an email.
